config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root  'home#index'
  get   'home/about'
  get   'home/lookup'
  post "/home/lookup" => 'home/lookup'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!

  # GET /cryptos or /cryptos.json
  def index
    @cryptos = Crypto.all
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to crypto_url(@crypto), notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to crypto_url(@crypto), notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy

    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  BASE_URL = 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
  API_SECRET_KEY = "5e4c208b-f863-45f1-887f-6819aae42893"

  def index
    @url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=#{API_SECRET_KEY}&start=1&limit=5000&convert=USD"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "ETH", "BNB", "ADA"]
  end

  def about

  end

  def lookup
    @url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=#{API_SECRET_KEY}&start=1&limit=5000&convert=USD"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @look_up_coin = JSON.parse(@response)

    @symbol = params[:sym]
    if @symbol
      @symbol = @symbol.upcase
    end

    if @symbol == ""
      @symbol = "Please enter a crypto currency"
    end
  end

  def number_as_decimal(number, decimals)
    number_with_precision(number, precision: decimals)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<div class="row justify-content-md-center">
  <div class="card" style="width: 20rem;">
    <div class="card-body">
      <h5 class="card-title">Sign Up</h5>

      <p class="card-text">
        <%= form_with(model: crypto) do |f| %>
        <% if crypto.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

            <ul>
              <% crypto.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= f.label :symbol, class: "form-label" %><br />
          <%= f.text_field :symbol, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :user_id, class: "form-label" %><br />
          <%= f.number_field :user_id, value: current_user.id, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :cost_per, class: "form-label" %><br />
          <%= f.text_field :cost_per, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :amount_owned, class: "form-label" %><br />
          <%= f.text_field :amount_owned, class: "form-control" %>
        </div>


        <div class="actions">
          <%= f.submit "Sign up", class: "btn btn-warning" %>
        </div>
        <% end %>
      </p>
      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>Cryptos</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Symbol</th>
      <th>User</th>
      <th>Cost per</th>
      <th>Amount owned</th>
      <th class="text-center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
    <tr class="table-card">
      <td class="crypto-symbol"><%= crypto.symbol.upcase %></td>
      <td><%= crypto.user_id %></td>
      <td>$ <%= crypto.cost_per %></td>
      <td>$ <%= crypto.amount_owned %></td>
      <td class="text-center">
        <%= link_to crypto do %>
        <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= link_to edit_crypto_path(crypto) do %>
        <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= link_to 'Destroy', crypto, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <tr class="spacer"></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crypto', new_crypto_path %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Symbol</th>
      <th>User</th>
      <th>Cost per</th>
      <th>Amount Owned</th>
    </tr>
  </thead>
  <tbody>
    <tr class="alert" role="alert">
      <td><%= @crypto.symbol %></td>
      <td><%= @crypto.user_id %></td>
      <td><%= @crypto.cost_per %></td>
      <td><%= @crypto.amount_owned %></td>
      <td>
        <a href="#" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true"><i class="fa fa-close"></i></span>
        </a>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %>

app/views/home/about.html.erb
<h1>About page</h1>
<%= @hello %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% for x in @coins["data"] %>
  <% for coin in @my_coins %>
    <% if coin == x["symbol"] %>
      <%= x["name"] %>: $<%= x["quote"]["USD"]["price"]%><br />
      Rank: <%= x["cmc_rank"] %><br /><br />
    <% end %>
  <% end %>
<% end %>

app/views/home/lookup.html.erb
<h3>Crypto Currency Lookup</h3>

<%= form_tag home_lookup_path, :method => "POST" do %>
<%= text_field_tag "sym", nil, placeholder: "Enter Crypto Symbol", size: 50 %>
<%= submit_tag 'Lookup Stock Price' %>
<% end %>

<% if @symbol %>
  <% for x in @look_up_coin["data"] %>
    <% if @symbol == x["symbol"] %>
      <div class="card text-white bg-dark mt-3 mb-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title mb-2"><%= x["name"] %></h5>
          <p class="card-text mb-0">$ <%= x["quote"]["USD"]["price"] %></p>
          <p class="card-text mb-0">Rank: <%= x["cmc_rank"] %></p>
          <p class="card-text mb-0">24h Change: <%= x["quote"]["USD"]["percent_change_24h"] %></p>
          <div class="card-body mt-3 p-0">
            <a href="#" class="btn btn-info">Track Coin</a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>

<div class="alert alert-warning d-flex align-items-center" role="alert">
  <i class="bi bi-bell pe-2"></i>
  <div>
    <%= content_tag(:div, msg) %>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Crypto Tracker', root_path, class: "navbar-brand"%>
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Lookup', home_lookup_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav d-flex">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My Cryptos', cryptos_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add New', new_crypto_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            My Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="mb-3">
              <%= link_to  edit_user_registration_path, class: "dropdown-item" do %>
                <i class="bi bi-gear"></i>
                <span class="ms-1">Edit Profile</span>
              <% end %>
            </li>
            <li class="mb-3"><hr class="dropdown-divider"></li>
            <li class="text-center">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <button class="btn btn-warning ">Log Out</button>
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
            </li>

          </ul>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CryptoRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <div class="container mt-4">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
</body>
</html>